# DESeq2 script generated by iDEP on Wed Dec 10 15:18:55 2025
# Please cite https://doi.org/10.1186/s12859-018-2486-6

# R version 4.5.1 (2025-06-13)
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")  # v. 1.30.26
if (!require("DESeq2", quietly = TRUE))
  BiocManager::install("DESeq2")  # v. 1.48.2
library(DESeq2) # D.E.G.
FC <- 2 # Fold-change cutoff
FDR <- 0.1 # FDR cutoff
alpha <- 0.1 # independent filtering, default

#  Prepare data --------------------
# Use the "Converted counts" button in the Pre-Process tab
# to download the filtered counts file with gene IDs converted to Ensembl.
raw_counts = read.csv("converted_counts_data.csv")
row.names(raw_counts) <- raw_counts$User_ID
raw_counts <- raw_counts[, -(1:3)] # delete 3 columns of IDs
str(raw_counts)

# Factors coded: condition --> A, preservative --> B, genotype --> C, Treatment_genotype --> D
col_data <- data.frame(
  "A" = c("0_CGY", "0_CGY", "0_CGY", "0_CGY", "0_CGY", "0_CGY", "0_CGY", "0_CGY", "40_CGY", "40_CGY", "40_CGY", "40_CGY", "40_CGY", "40_CGY", "40_CGY", "40_CGY", "0_CGY", "0_CGY", "0_CGY", "0_CGY", "0_CGY", "0_CGY", "0_CGY", "0_CGY", "40_CGY", "40_CGY", "40_CGY", "40_CGY", "40_CGY", "40_CGY", "40_CGY"),
  "B" = c("DRS", "DRS", "DRS", "DRS", "RL", "RL", "RL", "RL", "DRS", "DRS", "DRS", "DRS", "RL", "RL", "RL", "RL", "DRS", "DRS", "DRS", "DRS", "RL", "RL", "RL", "RL", "DRS", "DRS", "DRS", "DRS", "RL", "RL", "RL"),
  "C" = c("ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "ANTHO_LESS", "WT", "WT", "WT", "WT", "WT", "WT", "WT", "WT", "WT", "WT", "WT", "WT", "WT", "WT", "WT"),
  "D" = c("ANTHO_LESS_&_0_CGY", "ANTHO_LESS_&_0_CGY", "ANTHO_LESS_&_0_CGY", "ANTHO_LESS_&_0_CGY", "ANTHO_LESS_&_0_CGY", "ANTHO_LESS_&_0_CGY", "ANTHO_LESS_&_0_CGY", "ANTHO_LESS_&_0_CGY", "ANTHO_LESS_&_40_CGY", "ANTHO_LESS_&_40_CGY", "ANTHO_LESS_&_40_CGY", "ANTHO_LESS_&_40_CGY", "ANTHO_LESS_&_40_CGY", "ANTHO_LESS_&_40_CGY", "ANTHO_LESS_&_40_CGY", "ANTHO_LESS_&_40_CGY", "WT_&_0_CGY", "WT_&_0_CGY", "WT_&_0_CGY", "WT_&_0_CGY", "WT_&_0_CGY", "WT_&_0_CGY", "WT_&_0_CGY", "WT_&_0_CGY", "WT_&_40_CGY", "WT_&_40_CGY", "WT_&_40_CGY", "WT_&_40_CGY", "WT_&_40_CGY", "WT_&_40_CGY", "WT_&_40_CGY")
)
row.names(col_data) <- colnames(raw_counts)
col_data

#Set reference level 
col_data[, 4] <- as.factor(col_data[, 4])
col_data[, 4] <- relevel(col_data[, 4], "WT_&_0_CGY")
col_data[, 4] <- as.factor(col_data[, 4])
col_data[, 4] <- relevel(col_data[, 4], "ANTHO_LESS_&_0_CGY")

# Run DESeq2--------------------
DESeq2::DESeqDataSetFromMatrix(
   countData = raw_counts,
   colData = col_data,
   design = ~  D + B 
)
dds = DESeq2::DESeq(dds) 

# Extract results--------------------

# Comparison 1 of 4:  ANTHO_LESS_&_0_CGY-WT_&_0_CGY
res <- DESeq2::results(dds,
  contrast = c("D", "ANTHO_LESS_&_0_CGY", "WT_&_0_CGY"),
  independentFiltering = FALSE,
  alpha = alpha
)
# Examine results 
summary(res)
plotMA(res)
plotCounts(dds, gene = which.min(res$padj), intgroup = colnames(col_data)[2])
res <- subset(res, padj < FDR & abs(log2FoldChange) > log2(FC)) # Select
table(sign(res$log2FoldChange)) # N. of genes Down, Up
res <- res[order(-res$log2FoldChange), ] #sort
head(res) #top upregulated
tail(res) #top downregulated

# Comparison 2 of 4:  ANTHO_LESS_&_40_CGY-ANTHO_LESS_&_0_CGY
res <- DESeq2::results(dds,
  contrast = c("D", "ANTHO_LESS_&_40_CGY", "ANTHO_LESS_&_0_CGY"),
  independentFiltering = FALSE,
  alpha = alpha
)
# Examine results 
summary(res)
plotMA(res)
plotCounts(dds, gene = which.min(res$padj), intgroup = colnames(col_data)[2])
res <- subset(res, padj < FDR & abs(log2FoldChange) > log2(FC)) # Select
table(sign(res$log2FoldChange)) # N. of genes Down, Up
res <- res[order(-res$log2FoldChange), ] #sort
head(res) #top upregulated
tail(res) #top downregulated

# Comparison 3 of 4:  ANTHO_LESS_&_40_CGY-WT_&_40_CGY
res <- DESeq2::results(dds,
  contrast = c("D", "ANTHO_LESS_&_40_CGY", "WT_&_40_CGY"),
  independentFiltering = FALSE,
  alpha = alpha
)
# Examine results 
summary(res)
plotMA(res)
plotCounts(dds, gene = which.min(res$padj), intgroup = colnames(col_data)[2])
res <- subset(res, padj < FDR & abs(log2FoldChange) > log2(FC)) # Select
table(sign(res$log2FoldChange)) # N. of genes Down, Up
res <- res[order(-res$log2FoldChange), ] #sort
head(res) #top upregulated
tail(res) #top downregulated

# Comparison 4 of 4:  WT_&_40_CGY-WT_&_0_CGY
res <- DESeq2::results(dds,
  contrast = c("D", "WT_&_40_CGY", "WT_&_0_CGY"),
  independentFiltering = FALSE,
  alpha = alpha
)
# Examine results 
summary(res)
plotMA(res)
plotCounts(dds, gene = which.min(res$padj), intgroup = colnames(col_data)[2])
res <- subset(res, padj < FDR & abs(log2FoldChange) > log2(FC)) # Select
table(sign(res$log2FoldChange)) # N. of genes Down, Up
res <- res[order(-res$log2FoldChange), ] #sort
head(res) #top upregulated
tail(res) #top downregulated

